name: gather
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  flutter_native_splash: ^2.0.4
  flutter_svg: ^1.0.3
  flutterfire_ui: ^0.3.6+1
  freezed_annotation: ^1.1.0
  hooks_riverpod: ^1.0.3

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1

flutter:
  assets:
    - assets/loading/
  
  fonts:
    - family: SFProRounded
      fonts: 
        - asset: assets/fonts/SF-Pro-Rounded-Ultralight.ttf
          weight: 100
        - asset: assets/fonts/SF-Pro-Rounded-Thin.ttf
          weight: 200
        - asset: assets/fonts/SF-Pro-Rounded-Light.ttf
          weight: 300
        - asset: assets/fonts/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-Pro-Rounded-Medium.ttf
          weight: 500
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SF-Pro-Rounded-Bold.ttf
          weight: 700
        - asset: assets/fonts/SF-Pro-Rounded-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SF-Pro-Rounded-Black.ttf
          weight: 900
  
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FA4A0C"
  image: assets/splash/splash.png
  android_12:
    image: assets/splash/splash.png
    icon_background_color: "#FA4A0C"
  web: false
  fullscreen: true

