// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6dR4QLzw6cl3CG8L252zUWWc5ONpsdyM',
    appId: '1:1067059935185:android:26c7cc11c05d3bcd1352f0',
    messagingSenderId: '1067059935185',
    projectId: 'gather-sg',
    storageBucket: 'gather-sg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqiJndGYdGEkCKQGF80e--jYm38qrs42Q',
    appId: '1:1067059935185:ios:0a3a591ae89ca1031352f0',
    messagingSenderId: '1067059935185',
    projectId: 'gather-sg',
    storageBucket: 'gather-sg.appspot.com',
    iosClientId: '1067059935185-hln2b0dsq1r1moc5smvqhasvu4b58cv1.apps.googleusercontent.com',
    iosBundleId: 'sg.app.gather',
  );
}
