name: Automated Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2.3.0

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib

      - name: Analyze
        run: flutter analyze lib --no-fatal-infos --no-fatal-warnings

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
